name: Release Creation

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Get the tag name
      - name: Get Version
        id: get-version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      # Create a zip file
      - name: Create ZIP
        run: |
          # Ensure the zip excludes unnecessary files
          zip -r ./module.zip \
            module.json \
            README.md \
            LICENSE \
            scripts/ \
            styles/ \
            templates/ \
            languages/ \
            -x '*.git*' -x '*.github*' -x '*.vscode*'
          
          # Copy module.json to release
          cp module.json ./module.json

      # Create the release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: './module.zip,./module.json'
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          generateReleaseNotes: true 